"""sync_reservations_and_hms_schema

Revision ID: 8378c8dce28c
Revises: 5eb71fbec071
Create Date: 2026-03-17 19:16:58.851709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8378c8dce28c'
down_revision: Union[str, None] = '5eb71fbec071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_owner'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_audit_events_actor_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_source_module'), table_name='audit_events')
    op.alter_column('auto_purchase_rules', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_auto_purchase_rules_restaurant_id'), table_name='auto_purchase_rules')
    op.alter_column('bills', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_bills_restaurant_id'), table_name='bills')
    op.alter_column('cash_shifts', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_cash_shifts_restaurant_id'), table_name='cash_shifts')
    op.alter_column('floor_sections', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_floor_sections_restaurant_id'), table_name='floor_sections')
    op.alter_column('guest_profiles', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('hms_reservations', sa.Column('guest_phone', sa.String(length=50), nullable=True))
    op.add_column('hms_reservations', sa.Column('adults', sa.Integer(), nullable=True))
    op.execute("UPDATE hms_reservations SET adults = 1 WHERE adults IS NULL")
    op.alter_column('hms_reservations', 'adults', nullable=False)

    op.add_column('hms_reservations', sa.Column('children', sa.Integer(), nullable=True))
    op.execute("UPDATE hms_reservations SET children = 0 WHERE children IS NULL")
    op.alter_column('hms_reservations', 'children', nullable=False)
    op.add_column('hms_reservations', sa.Column('room_type_id', sa.Integer(), nullable=True))
    op.add_column('hms_reservations', sa.Column('payment_status', sa.String(length=20), nullable=True))
    op.execute("UPDATE hms_reservations SET payment_status = 'pending' WHERE payment_status IS NULL")
    op.alter_column('hms_reservations', 'payment_status', nullable=False)

    op.add_column('hms_reservations', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))

    op.add_column('hms_reservations', sa.Column('booking_id', sa.String(length=50), nullable=True))
    op.execute("UPDATE hms_reservations SET booking_id = 'TEMP-' || id WHERE booking_id IS NULL")
    op.alter_column('hms_reservations', 'booking_id', nullable=False)

    op.create_index(op.f('ix_hms_reservations_booking_id'), 'hms_reservations', ['booking_id'], unique=True)
    op.create_foreign_key(None, 'hms_reservations', 'hms_room_types', ['room_type_id'], ['id'], ondelete='SET NULL')
    op.alter_column('inventory_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory_movements', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_inventory_movements_restaurant_id'), table_name='inventory_movements')
    op.alter_column('kds_station_configs', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_kds_station_configs_restaurant_id'), table_name='kds_station_configs')
    op.alter_column('loyalty_accounts', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_loyalty_accounts_restaurant_id'), table_name='loyalty_accounts')
    op.alter_column('menu_categories', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu_combos', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_menu_combos_restaurant_id'), table_name='menu_combos')
    op.alter_column('menu_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu_modifiers', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_menu_modifiers_restaurant_id'), table_name='menu_modifiers')
    op.alter_column('order_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_order_items_restaurant_id'), table_name='order_items')
    op.alter_column('orders', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_orders_restaurant_id'), table_name='orders')
    op.alter_column('payments', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_payments_restaurant_id'), table_name='payments')
    op.alter_column('promotions', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_promotions_restaurant_id'), table_name='promotions')
    op.alter_column('purchase_orders', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('qr_table_codes', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_qr_table_codes_restaurant_id'), table_name='qr_table_codes')
    op.add_column('reservations', sa.Column('payment_status', sa.String(length=20), nullable=True))
    op.execute("UPDATE reservations SET payment_status = 'pending' WHERE payment_status IS NULL")
    op.alter_column('reservations', 'payment_status', nullable=False)
    op.add_column('reservations', sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True))
    op.alter_column('reservations', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_revenue_control_policies_restaurant_id'), table_name='revenue_control_policies')
    op.drop_index(op.f('ix_revenue_experiment_events_experiment_variant'), table_name='revenue_experiment_events')
    op.drop_index(op.f('ix_revenue_experiment_events_restaurant_recorded'), table_name='revenue_experiment_events')
    op.drop_index(op.f('ix_revenue_experiments_restaurant_status'), table_name='revenue_experiments')
    op.drop_index(op.f('ix_revenue_upsell_recommendations_restaurant_generated'), table_name='revenue_upsell_recommendations')
    op.drop_index(op.f('ix_service_autopilot_predictions_restaurant_target'), table_name='service_autopilot_predictions')
    op.drop_index(op.f('ix_service_autopilot_predictions_table_generated'), table_name='service_autopilot_predictions')
    op.alter_column('supplier_catalog_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_supplier_catalog_items_restaurant_id'), table_name='supplier_catalog_items')
    op.alter_column('table_orders', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('table_sessions', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_table_sessions_restaurant_id'), table_name='table_sessions')
    op.alter_column('tables', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tva_reports', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_tva_reports_restaurant_id'), table_name='tva_reports')
    op.alter_column('upsell_rules', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_upsell_rules_restaurant_id'), table_name='upsell_rules')
    op.alter_column('vendors', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('waitlist', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_waitlist_restaurant_id'), table_name='waitlist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_waitlist_restaurant_id'), 'waitlist', ['restaurant_id'], unique=False)
    op.alter_column('waitlist', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendors', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_upsell_rules_restaurant_id'), 'upsell_rules', ['restaurant_id'], unique=False)
    op.alter_column('upsell_rules', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tva_reports_restaurant_id'), 'tva_reports', ['restaurant_id'], unique=False)
    op.alter_column('tva_reports', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tables', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_table_sessions_restaurant_id'), 'table_sessions', ['restaurant_id'], unique=False)
    op.alter_column('table_sessions', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('table_orders', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_supplier_catalog_items_restaurant_id'), 'supplier_catalog_items', ['restaurant_id'], unique=False)
    op.alter_column('supplier_catalog_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_service_autopilot_predictions_table_generated'), 'service_autopilot_predictions', ['table_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_service_autopilot_predictions_restaurant_target'), 'service_autopilot_predictions', ['restaurant_id', 'target_time'], unique=False)
    op.create_index(op.f('ix_revenue_upsell_recommendations_restaurant_generated'), 'revenue_upsell_recommendations', ['restaurant_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_revenue_experiments_restaurant_status'), 'revenue_experiments', ['restaurant_id', 'status'], unique=False)
    op.create_index(op.f('ix_revenue_experiment_events_restaurant_recorded'), 'revenue_experiment_events', ['restaurant_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_revenue_experiment_events_experiment_variant'), 'revenue_experiment_events', ['experiment_id', 'variant_key'], unique=False)
    op.create_index(op.f('ix_revenue_control_policies_restaurant_id'), 'revenue_control_policies', ['restaurant_id'], unique=False)
    op.alter_column('reservations', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reservations', 'stripe_payment_intent_id')
    op.drop_column('reservations', 'payment_status')
    op.create_index(op.f('ix_qr_table_codes_restaurant_id'), 'qr_table_codes', ['restaurant_id'], unique=False)
    op.alter_column('qr_table_codes', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('purchase_orders', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_promotions_restaurant_id'), 'promotions', ['restaurant_id'], unique=False)
    op.alter_column('promotions', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_payments_restaurant_id'), 'payments', ['restaurant_id'], unique=False)
    op.alter_column('payments', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_orders_restaurant_id'), 'orders', ['restaurant_id'], unique=False)
    op.alter_column('orders', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_order_items_restaurant_id'), 'order_items', ['restaurant_id'], unique=False)
    op.alter_column('order_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_menu_modifiers_restaurant_id'), 'menu_modifiers', ['restaurant_id'], unique=False)
    op.alter_column('menu_modifiers', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_menu_combos_restaurant_id'), 'menu_combos', ['restaurant_id'], unique=False)
    op.alter_column('menu_combos', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu_categories', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_loyalty_accounts_restaurant_id'), 'loyalty_accounts', ['restaurant_id'], unique=False)
    op.alter_column('loyalty_accounts', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_kds_station_configs_restaurant_id'), 'kds_station_configs', ['restaurant_id'], unique=False)
    op.alter_column('kds_station_configs', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_inventory_movements_restaurant_id'), 'inventory_movements', ['restaurant_id'], unique=False)
    op.alter_column('inventory_movements', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory_items', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'hms_reservations', type_='foreignkey')
    op.drop_index(op.f('ix_hms_reservations_booking_id'), table_name='hms_reservations')
    op.drop_column('hms_reservations', 'booking_id')
    op.drop_column('hms_reservations', 'stripe_payment_intent_id')
    op.drop_column('hms_reservations', 'payment_status')
    op.drop_column('hms_reservations', 'room_type_id')
    op.drop_column('hms_reservations', 'children')
    op.drop_column('hms_reservations', 'adults')
    op.drop_column('hms_reservations', 'guest_phone')
    op.alter_column('guest_profiles', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_floor_sections_restaurant_id'), 'floor_sections', ['restaurant_id'], unique=False)
    op.alter_column('floor_sections', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_cash_shifts_restaurant_id'), 'cash_shifts', ['restaurant_id'], unique=False)
    op.alter_column('cash_shifts', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_bills_restaurant_id'), 'bills', ['restaurant_id'], unique=False)
    op.alter_column('bills', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_auto_purchase_rules_restaurant_id'), 'auto_purchase_rules', ['restaurant_id'], unique=False)
    op.alter_column('auto_purchase_rules', 'restaurant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_audit_events_source_module'), 'audit_events', ['source_module'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type_entity_id'), 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_type'), 'audit_events', ['actor_type'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_owner'), 'alerts', ['owner'], unique=False)
    # ### end Alembic commands ###
